export interface Country {
  code: string;
  name: string;
  flag: string;
}

/**
 * Convert ISO 3166-1 alpha-2 country code to flag emoji
 */
function codeToFlag(code: string): string {
  const codePoints = code
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

/**
 * List of countries with ISO 3166-1 alpha-2 codes
 */
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: codeToFlag("AF") },
  { code: "AL", name: "Albania", flag: codeToFlag("AL") },
  { code: "DZ", name: "Algeria", flag: codeToFlag("DZ") },
  { code: "AD", name: "Andorra", flag: codeToFlag("AD") },
  { code: "AO", name: "Angola", flag: codeToFlag("AO") },
  { code: "AG", name: "Antigua and Barbuda", flag: codeToFlag("AG") },
  { code: "AR", name: "Argentina", flag: codeToFlag("AR") },
  { code: "AM", name: "Armenia", flag: codeToFlag("AM") },
  { code: "AU", name: "Australia", flag: codeToFlag("AU") },
  { code: "AT", name: "Austria", flag: codeToFlag("AT") },
  { code: "AZ", name: "Azerbaijan", flag: codeToFlag("AZ") },
  { code: "BS", name: "Bahamas", flag: codeToFlag("BS") },
  { code: "BH", name: "Bahrain", flag: codeToFlag("BH") },
  { code: "BD", name: "Bangladesh", flag: codeToFlag("BD") },
  { code: "BB", name: "Barbados", flag: codeToFlag("BB") },
  { code: "BY", name: "Belarus", flag: codeToFlag("BY") },
  { code: "BE", name: "Belgium", flag: codeToFlag("BE") },
  { code: "BZ", name: "Belize", flag: codeToFlag("BZ") },
  { code: "BJ", name: "Benin", flag: codeToFlag("BJ") },
  { code: "BT", name: "Bhutan", flag: codeToFlag("BT") },
  { code: "BO", name: "Bolivia", flag: codeToFlag("BO") },
  { code: "BA", name: "Bosnia and Herzegovina", flag: codeToFlag("BA") },
  { code: "BW", name: "Botswana", flag: codeToFlag("BW") },
  { code: "BR", name: "Brazil", flag: codeToFlag("BR") },
  { code: "BN", name: "Brunei", flag: codeToFlag("BN") },
  { code: "BG", name: "Bulgaria", flag: codeToFlag("BG") },
  { code: "BF", name: "Burkina Faso", flag: codeToFlag("BF") },
  { code: "BI", name: "Burundi", flag: codeToFlag("BI") },
  { code: "CV", name: "Cabo Verde", flag: codeToFlag("CV") },
  { code: "KH", name: "Cambodia", flag: codeToFlag("KH") },
  { code: "CM", name: "Cameroon", flag: codeToFlag("CM") },
  { code: "CA", name: "Canada", flag: codeToFlag("CA") },
  { code: "CF", name: "Central African Republic", flag: codeToFlag("CF") },
  { code: "TD", name: "Chad", flag: codeToFlag("TD") },
  { code: "CL", name: "Chile", flag: codeToFlag("CL") },
  { code: "CN", name: "China", flag: codeToFlag("CN") },
  { code: "CO", name: "Colombia", flag: codeToFlag("CO") },
  { code: "KM", name: "Comoros", flag: codeToFlag("KM") },
  { code: "CG", name: "Congo", flag: codeToFlag("CG") },
  { code: "CR", name: "Costa Rica", flag: codeToFlag("CR") },
  { code: "HR", name: "Croatia", flag: codeToFlag("HR") },
  { code: "CU", name: "Cuba", flag: codeToFlag("CU") },
  { code: "CY", name: "Cyprus", flag: codeToFlag("CY") },
  { code: "CZ", name: "Czech Republic", flag: codeToFlag("CZ") },
  { code: "DK", name: "Denmark", flag: codeToFlag("DK") },
  { code: "DJ", name: "Djibouti", flag: codeToFlag("DJ") },
  { code: "DM", name: "Dominica", flag: codeToFlag("DM") },
  { code: "DO", name: "Dominican Republic", flag: codeToFlag("DO") },
  { code: "EC", name: "Ecuador", flag: codeToFlag("EC") },
  { code: "EG", name: "Egypt", flag: codeToFlag("EG") },
  { code: "SV", name: "El Salvador", flag: codeToFlag("SV") },
  { code: "GQ", name: "Equatorial Guinea", flag: codeToFlag("GQ") },
  { code: "ER", name: "Eritrea", flag: codeToFlag("ER") },
  { code: "EE", name: "Estonia", flag: codeToFlag("EE") },
  { code: "SZ", name: "Eswatini", flag: codeToFlag("SZ") },
  { code: "ET", name: "Ethiopia", flag: codeToFlag("ET") },
  { code: "FJ", name: "Fiji", flag: codeToFlag("FJ") },
  { code: "FI", name: "Finland", flag: codeToFlag("FI") },
  { code: "FR", name: "France", flag: codeToFlag("FR") },
  { code: "GA", name: "Gabon", flag: codeToFlag("GA") },
  { code: "GM", name: "Gambia", flag: codeToFlag("GM") },
  { code: "GE", name: "Georgia", flag: codeToFlag("GE") },
  { code: "DE", name: "Germany", flag: codeToFlag("DE") },
  { code: "GH", name: "Ghana", flag: codeToFlag("GH") },
  { code: "GR", name: "Greece", flag: codeToFlag("GR") },
  { code: "GD", name: "Grenada", flag: codeToFlag("GD") },
  { code: "GT", name: "Guatemala", flag: codeToFlag("GT") },
  { code: "GN", name: "Guinea", flag: codeToFlag("GN") },
  { code: "GW", name: "Guinea-Bissau", flag: codeToFlag("GW") },
  { code: "GY", name: "Guyana", flag: codeToFlag("GY") },
  { code: "HT", name: "Haiti", flag: codeToFlag("HT") },
  { code: "HN", name: "Honduras", flag: codeToFlag("HN") },
  { code: "HK", name: "Hong Kong", flag: codeToFlag("HK") },
  { code: "HU", name: "Hungary", flag: codeToFlag("HU") },
  { code: "IS", name: "Iceland", flag: codeToFlag("IS") },
  { code: "IN", name: "India", flag: codeToFlag("IN") },
  { code: "ID", name: "Indonesia", flag: codeToFlag("ID") },
  { code: "IR", name: "Iran", flag: codeToFlag("IR") },
  { code: "IQ", name: "Iraq", flag: codeToFlag("IQ") },
  { code: "IE", name: "Ireland", flag: codeToFlag("IE") },
  { code: "IL", name: "Israel", flag: codeToFlag("IL") },
  { code: "IT", name: "Italy", flag: codeToFlag("IT") },
  { code: "CI", name: "Ivory Coast", flag: codeToFlag("CI") },
  { code: "JM", name: "Jamaica", flag: codeToFlag("JM") },
  { code: "JP", name: "Japan", flag: codeToFlag("JP") },
  { code: "JO", name: "Jordan", flag: codeToFlag("JO") },
  { code: "KZ", name: "Kazakhstan", flag: codeToFlag("KZ") },
  { code: "KE", name: "Kenya", flag: codeToFlag("KE") },
  { code: "KI", name: "Kiribati", flag: codeToFlag("KI") },
  { code: "KW", name: "Kuwait", flag: codeToFlag("KW") },
  { code: "KG", name: "Kyrgyzstan", flag: codeToFlag("KG") },
  { code: "LA", name: "Laos", flag: codeToFlag("LA") },
  { code: "LV", name: "Latvia", flag: codeToFlag("LV") },
  { code: "LB", name: "Lebanon", flag: codeToFlag("LB") },
  { code: "LS", name: "Lesotho", flag: codeToFlag("LS") },
  { code: "LR", name: "Liberia", flag: codeToFlag("LR") },
  { code: "LY", name: "Libya", flag: codeToFlag("LY") },
  { code: "LI", name: "Liechtenstein", flag: codeToFlag("LI") },
  { code: "LT", name: "Lithuania", flag: codeToFlag("LT") },
  { code: "LU", name: "Luxembourg", flag: codeToFlag("LU") },
  { code: "MG", name: "Madagascar", flag: codeToFlag("MG") },
  { code: "MW", name: "Malawi", flag: codeToFlag("MW") },
  { code: "MY", name: "Malaysia", flag: codeToFlag("MY") },
  { code: "MV", name: "Maldives", flag: codeToFlag("MV") },
  { code: "ML", name: "Mali", flag: codeToFlag("ML") },
  { code: "MT", name: "Malta", flag: codeToFlag("MT") },
  { code: "MH", name: "Marshall Islands", flag: codeToFlag("MH") },
  { code: "MR", name: "Mauritania", flag: codeToFlag("MR") },
  { code: "MU", name: "Mauritius", flag: codeToFlag("MU") },
  { code: "MX", name: "Mexico", flag: codeToFlag("MX") },
  { code: "FM", name: "Micronesia", flag: codeToFlag("FM") },
  { code: "MD", name: "Moldova", flag: codeToFlag("MD") },
  { code: "MC", name: "Monaco", flag: codeToFlag("MC") },
  { code: "MN", name: "Mongolia", flag: codeToFlag("MN") },
  { code: "ME", name: "Montenegro", flag: codeToFlag("ME") },
  { code: "MA", name: "Morocco", flag: codeToFlag("MA") },
  { code: "MZ", name: "Mozambique", flag: codeToFlag("MZ") },
  { code: "MM", name: "Myanmar", flag: codeToFlag("MM") },
  { code: "NA", name: "Namibia", flag: codeToFlag("NA") },
  { code: "NR", name: "Nauru", flag: codeToFlag("NR") },
  { code: "NP", name: "Nepal", flag: codeToFlag("NP") },
  { code: "NL", name: "Netherlands", flag: codeToFlag("NL") },
  { code: "NZ", name: "New Zealand", flag: codeToFlag("NZ") },
  { code: "NI", name: "Nicaragua", flag: codeToFlag("NI") },
  { code: "NE", name: "Niger", flag: codeToFlag("NE") },
  { code: "NG", name: "Nigeria", flag: codeToFlag("NG") },
  { code: "KP", name: "North Korea", flag: codeToFlag("KP") },
  { code: "MK", name: "North Macedonia", flag: codeToFlag("MK") },
  { code: "NO", name: "Norway", flag: codeToFlag("NO") },
  { code: "OM", name: "Oman", flag: codeToFlag("OM") },
  { code: "PK", name: "Pakistan", flag: codeToFlag("PK") },
  { code: "PW", name: "Palau", flag: codeToFlag("PW") },
  { code: "PS", name: "Palestine", flag: codeToFlag("PS") },
  { code: "PA", name: "Panama", flag: codeToFlag("PA") },
  { code: "PG", name: "Papua New Guinea", flag: codeToFlag("PG") },
  { code: "PY", name: "Paraguay", flag: codeToFlag("PY") },
  { code: "PE", name: "Peru", flag: codeToFlag("PE") },
  { code: "PH", name: "Philippines", flag: codeToFlag("PH") },
  { code: "PL", name: "Poland", flag: codeToFlag("PL") },
  { code: "PT", name: "Portugal", flag: codeToFlag("PT") },
  { code: "QA", name: "Qatar", flag: codeToFlag("QA") },
  { code: "RO", name: "Romania", flag: codeToFlag("RO") },
  { code: "RU", name: "Russia", flag: codeToFlag("RU") },
  { code: "RW", name: "Rwanda", flag: codeToFlag("RW") },
  { code: "KN", name: "Saint Kitts and Nevis", flag: codeToFlag("KN") },
  { code: "LC", name: "Saint Lucia", flag: codeToFlag("LC") },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: codeToFlag("VC") },
  { code: "WS", name: "Samoa", flag: codeToFlag("WS") },
  { code: "SM", name: "San Marino", flag: codeToFlag("SM") },
  { code: "ST", name: "Sao Tome and Principe", flag: codeToFlag("ST") },
  { code: "SA", name: "Saudi Arabia", flag: codeToFlag("SA") },
  { code: "SN", name: "Senegal", flag: codeToFlag("SN") },
  { code: "RS", name: "Serbia", flag: codeToFlag("RS") },
  { code: "SC", name: "Seychelles", flag: codeToFlag("SC") },
  { code: "SL", name: "Sierra Leone", flag: codeToFlag("SL") },
  { code: "SG", name: "Singapore", flag: codeToFlag("SG") },
  { code: "SK", name: "Slovakia", flag: codeToFlag("SK") },
  { code: "SI", name: "Slovenia", flag: codeToFlag("SI") },
  { code: "SB", name: "Solomon Islands", flag: codeToFlag("SB") },
  { code: "SO", name: "Somalia", flag: codeToFlag("SO") },
  { code: "ZA", name: "South Africa", flag: codeToFlag("ZA") },
  { code: "KR", name: "South Korea", flag: codeToFlag("KR") },
  { code: "SS", name: "South Sudan", flag: codeToFlag("SS") },
  { code: "ES", name: "Spain", flag: codeToFlag("ES") },
  { code: "LK", name: "Sri Lanka", flag: codeToFlag("LK") },
  { code: "SD", name: "Sudan", flag: codeToFlag("SD") },
  { code: "SR", name: "Suriname", flag: codeToFlag("SR") },
  { code: "SE", name: "Sweden", flag: codeToFlag("SE") },
  { code: "CH", name: "Switzerland", flag: codeToFlag("CH") },
  { code: "SY", name: "Syria", flag: codeToFlag("SY") },
  { code: "TW", name: "Taiwan", flag: codeToFlag("TW") },
  { code: "TJ", name: "Tajikistan", flag: codeToFlag("TJ") },
  { code: "TZ", name: "Tanzania", flag: codeToFlag("TZ") },
  { code: "TH", name: "Thailand", flag: codeToFlag("TH") },
  { code: "TL", name: "Timor-Leste", flag: codeToFlag("TL") },
  { code: "TG", name: "Togo", flag: codeToFlag("TG") },
  { code: "TO", name: "Tonga", flag: codeToFlag("TO") },
  { code: "TT", name: "Trinidad and Tobago", flag: codeToFlag("TT") },
  { code: "TN", name: "Tunisia", flag: codeToFlag("TN") },
  { code: "TR", name: "Turkey", flag: codeToFlag("TR") },
  { code: "TM", name: "Turkmenistan", flag: codeToFlag("TM") },
  { code: "TV", name: "Tuvalu", flag: codeToFlag("TV") },
  { code: "UG", name: "Uganda", flag: codeToFlag("UG") },
  { code: "UA", name: "Ukraine", flag: codeToFlag("UA") },
  { code: "AE", name: "United Arab Emirates", flag: codeToFlag("AE") },
  { code: "GB", name: "United Kingdom", flag: codeToFlag("GB") },
  { code: "US", name: "United States of America", flag: codeToFlag("US") },
  { code: "UY", name: "Uruguay", flag: codeToFlag("UY") },
  { code: "UZ", name: "Uzbekistan", flag: codeToFlag("UZ") },
  { code: "VU", name: "Vanuatu", flag: codeToFlag("VU") },
  { code: "VA", name: "Vatican City", flag: codeToFlag("VA") },
  { code: "VE", name: "Venezuela", flag: codeToFlag("VE") },
  { code: "VN", name: "Vietnam", flag: codeToFlag("VN") },
  { code: "YE", name: "Yemen", flag: codeToFlag("YE") },
  { code: "ZM", name: "Zambia", flag: codeToFlag("ZM") },
  { code: "ZW", name: "Zimbabwe", flag: codeToFlag("ZW") },
];

/**
 * Get country by ISO code
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

/**
 * Get country display string (flag + name)
 */
export function getCountryDisplay(code: string): string {
  const country = getCountryByCode(code);
  return country ? `${country.flag} ${country.name}` : code;
}

/**
 * Get country name by ISO code
 */
export function getCountryName(code: string): string | undefined {
  return getCountryByCode(code)?.name;
}
